### ISSUE TITLE
Missing Files / DIR Issues

### ISSUE THREAD

**Issue by Down2EarthGG** [Casterlabs/Casterlabs#12]
After branching the DEV on Linux, Ran NPM install and validated java, extensions and what not were installed, and the system had the correct administration rights (I am sure you know how Linux goes) ....

Running any of the build functions: npm run build/dev  lands in numerous errors with VITE and ENEONT's..

/Casterlabs-dev/__common/__common.mjs (imported by src/routes/app/__layout.svelte): 
ENOENT: no such file or directory, open '/home/rain/Desktop/Casterlabs-dev/__common/__common.mjs'

^- The above being one of the many. I am a unfamiliar with vite/svelte myself but wanted to pass this info a long. I can see you have already updated some documents in the branch as of yesterday (4/16). Perhaps there is more you all are working on~

Would appreciate some context or info about those developments when/if you can :)

**Comment by e3ndr** [comment]
Sorry that I'm just now seeing this (GitHub disabled notifications for some reason).

Developing should work on Linux or Windows or macOS. Personally I've successfully done so with Windows and macOS. 

Looks like I need to update the docs though, after installing all the dependencies listed in `caffeinated/`, run `./dev.sh` to fire up the development environment. That script will:
 - Copy the widget loader code into the app.
 - Start the dev server for the widgets (chat overlay, etc).
 - Start the dev server for the UI, which in turn starts the cloner program, fixing the ENOENT error.

That cloner program copies the contents of `__common/lib` into `caffeinated/ui/src/lib` and will synchronize the changes between them. This is needed because vite will not allow you to serve files outside of the project's base directory (which is `caffeinated/ui` in this case). We keep a separate `__common/lib` because in the future it'll be shared with CL Studio, as they'll have the same base for UI and everything.

If you need anymore help let me know :^)
